### ISSUE TITLE
Supporting Tomcat 8.5 and Java 10?

### ISSUE THREAD

**Issue by FranklinChen** [NCAR/joai-project#1]
As of last night, I had a setup of jOAI on Ubuntu 16.04 LTS which had been working fine all the way from Java 8 to Java 9 to Java 10 with Tomcat 8.0, but once I upgraded to Ubuntu 18.04 LTS, with Tomcat 8.5, jOAI no longer worked. I tried a fresh install from scratch, dropping in the `oai.war` file into the right place with `sudo cp joai_v3.2/oai.war /var/lib/tomcat8/webapps/` but the resulting Web page was empty. I can investigate other environmental factors, but I wonder if jOAI 3.2 has been tested with Tomcat 8.5 and Java 10.

More generally, I am curious what the plans are for further maintenance or development of jOAI. Since we are an OAI provider at http://oai.talkbank.org/oai (no longer working because of the "upgrade"), we need to know how to continue being so.

Note that Tomcat 8.0 is going end of life this summer: https://bugs.launchpad.net/ubuntu/+source/tomcat8/+bug/1712645

**Comment by FranklinChen** [comment]
I just installed Tomcat 9.0.7 manually on Ubuntu 18.04 LTS and jOAI works fine with it and Oracle Java 10. So now I am suspecting there is nothing wrong with jOAI. I will try a fresh installation of Tomcat 8.5.

**Comment by FranklinChen** [comment]
I did a fresh install of Tomcat 8.5.30 on Ubuntu 18.04 LTS and jOAI fails to work there. I guess I will consider this a bug in Tomcat 8.5.30!

You may want to make a note of this in the documentation.

**Comment by FranklinChen** [comment]
I verified that jOAI works with Tomcat 8.5.30 and the default Java (`default-jdk`) java-11-openjdk-amd64. The combination that did not work was when I used `oracle-java10-installer`.

**Comment by jweatherley** [comment]
I suspect that the oracle-java-10-installer installed in a way that Tomcat/jOAI could not see all the libraries that it needs. That's one of the most common problems I've encountered. Glad you were able to get it working with the default jdk and Tomcat 8.5.30.
