### ISSUE TITLE
splitting harvested files by set

### ISSUE THREAD

**Issue by markmatney** [NCAR/joai-project#2]
This issue is with the harvester. If you visit `/oai/admin/harvester.do?button=Add+new+harvest&scheduledHarvest=add`, at the bottom of the form is a radio input with label "When saving files:", and the two options are "Do not split by set" and "Split by set". If I click the question mark button next to the label, a popup comes up with the following text:

```
When saving files - Choose whether to keep saved files as a single group or split into sets. This option is active only if a setSpec is not specified.

Files being split by set are saved in a directory named after the setSpec.
```

This message and the behavior doesn't make sense to me. The option to split by set (i.e., save files to a directory named after the `setSpec`) would only make sense if there is a `setSpec` to begin with, so it should only be active if a `setSpec` IS specified.

**Comment by jweatherley** [comment]
When the data provider returns records to the harvester, it will indicate the sets (if any) for which each item belongs. The data provider will do so regardless of whether a setSpec is specified in the harvester's request. This is a feature of the OAI protocol.

The split-by-sets feature in jOAI is intended to make it possible to easily and automatically split the records into separate directories by setSpec when you harvest the entire repository.  Conversely, if you are interested in harvesting one or more sets individually, jOAI allows you to specify the setSpec you want to harvest and the specific directory you would like the items to be saved to.

**Comment by markmatney** [comment]
Ah, gotcha. I see now. I was misreading that popup. Thanks for the clarification.
