### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tomsaleeba** [NCAR/joai-project#3]
Hi, firstly thanks for the useful application.

We use jOAI as part of our infrastructure and I've created a Docker container to run it: https://github.com/ternaustralia/joai-docker.

**I'm wondering if you'd like me to send a PR so it can become part of this repo, or at least another repo in your NCAR GitHub account?**

On a side note, this Docker image uses OpenJDK to run the software, and I needed to [add two extra JARs](https://github.com/ternaustralia/joai-docker/blob/0368fc1e04ad16fd5af6d97d20a0c926728edeb2/Dockerfile#L8) to get things working: stax and woodstox. I'm not sure if this is a Tomcat thing or a jOAI thing, but perhaps someone else Googling for how to do this might stumble across this and get the help they need.

**Comment by jweatherley** [comment]
First, thank you for creating a Docker container for jOAI. I've long felt it would be a great option for deployment, glad you have done it! Also good info here for running under OpenJDK, I'm sure others will be interested to do so. 

Please send the PR, I think it would be nice to have it be part of the repo.

**Comment by jweatherley** [comment]
Docker support has been merged into the project. Thanks for contributing.
