### ISSUE TITLE
http://www.dlese.org/dpc/dds/tags/dleseELFunctions is not reachable

### ISSUE THREAD

**Issue by DigitLib** [NCAR/joai-project#7]
On start I got this message:
The absolute uri: [http://www.dlese.org/dpc/dds/tags/dleseELFunctions] cannot be resolved in either web.xml or the jar files deployed with this application

After checking the link it seems don't exist anymore.
App don't work.

How to solve this?

**Comment by jweatherley** [comment]
This message indicates that Tomcat cannot find the required Java class
files that are included in the application (the URI [
http://www.dlese.org/dpc/dds/tags/dleseELFunctions] does not resolve to a
URL on the internet but rather it references Java classes inside the
application).

When the app starts up, the class files inside oai.jar will unpack into the
WEB-INF directory, e.g. webapps/oai/WEB-INF/classes/org/dlese/dpc/...

It appears something is not properly installed or you may have an
incompatible version of Tomcat or the Java/JVM.

Note that jOAI was last verified to run under Tomcat 6, 7, or 8, and Java 8.

Be sure to closely follow the installation instructions here:
https://github.com/NCAR/joai-project/blob/master/web/docs/INSTALL.txt

Best regards,

John

**Comment by DigitLib** [comment]
Thank you! I have Tomcat 8.5.31 and jre 8_241

**Comment by DigitLib** [comment]
It work now! Thank you!
