### ISSUE TITLE
Links in documentation do not work

### ISSUE THREAD

**Issue by MiltosD** [NCAR/joai-project#8]
Hello,

It seems that all links related to https://www.dlese.org/ do not work. They resolve to a seemingly unrelated page.

**Comment by jweatherley** [comment]
Hello,

The DLESE digital library has been retired and it appears a new
organization has taken over the dlese.org web domain. Thanks for bringing
this to my attention, I will look at removing those links.

Information about DLESE can be found here:
https://aspace.archives.ucar.edu/repositories/2/resources/51

Best regards,
John

**Comment by jweatherley** [comment]
The web links to DLESE have been removed in version 3.3.
